name: notes
description: Flutter Notes
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # 网络
  dio: ^4.0.6
  # 状态管理
  get: ^4.6.5
  # 加密
  encrypt: ^5.0.1
  # 序列化
  json_annotation: ^4.5.0
  freezed_annotation: ^2.0.3
  # 键盘监听
  flutter_keyboard_visibility: ^5.2.0
  # 设备信息
  device_info_plus: ^4.0.0
  # Loading Toast Dialog
  flutter_smart_dialog: ^4.5.2
  # 日志
  logger: ^1.1.0
  # 文件目录
  path_provider: ^2.0.11
  # 下拉刷新
  # flutter_easyrefresh: ^2.2.1
  flutter_easy_refresh: 
    git: 
      url: 'https://github.com/xuelongqy/flutter_easyrefresh.git'
      ref: 'v3'
  pull_to_refresh_notification: ^2.3.0
  loading_more_list: any
  # 嵌套ScrollView
  extended_nested_scroll_view: ^6.0.0-dev.1
  # 图片
  extended_image: ^6.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  # 序列化
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  freezed: ^2.0.3+1
  # 自动化打包脚本
  cli:
    path: ./cli
  # AppIcon
  flutter_launcher_icons: ^0.9.2
  # LaunchImage
  flutter_native_splash: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/icon/
    - assets/images/launch/
   
flutter_icons:
  ios: true
  android: true
  image_path: assets/images/icon/icon.png
  remove_alpha_ios: true

flutter_native_splash:
  ios: true
  android: true
  web: false
  fullscreen: false
  color: '#FFFFFF'
  image: assets/images/launch/launch_light.png
  color_dark: '#0C0C0C'
  image_dark: assets/images/launch/launch_dark.png
  

