name: notes
description: Flutter Notes

version: 1.0.0+1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  # 自动化打包脚本
  cli:
    path: ./cli
  # AppIcon
  flutter_launcher_icons: ^0.9.2
  # LaunchImage
  flutter_native_splash: ^1.3.2

flutter:
  uses-material-design: true

flutter_icons:
  ios: true
  android: true
  image_path: assets/images/icon/icon.png
  remove_alpha_ios: true

flutter_native_splash:
  ios: true
  android: true
  web: false
  fullscreen: false
  color: '#FFFFFF'
  image: assets/images/launch/launch_light.png
  color_dark: '#0C0C0C'
  image_dark: assets/images/launch/launch_dark.png
  

