name: flutter_notes
description: Flutter Notes

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  # AppIcon
  flutter_launcher_icons: ^0.9.2
  # LaunchImage
  flutter_native_splash: ^1.3.3

flutter:
  uses-material-design: true

flutter_icons:
  ios: true
  android: true
  image_path: assets/images/icon/icon.png

flutter_native_splash:
  ios: true
  android: true
  fullscreen: true
  color: '#FFFFFF'
  image: assets/images/launch/launch_light.png
  color_dark: '#111010'
  image_dark: assets/images/launch/launch_dark.png
  

